
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-dining-s25-08
owner: ucsb-cs156-s25
repo_name: proj-dining-s25-08
pull_requests: [{"author":{"id":"MDQ6VXNlcjgwNjE0Mzg1","is_bot":false,"login":"giozucca","name":""},"headRefName":"gl-jsonfix","number":54,"title":"GL - jsonfix","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-08/pull/54"},{"author":{"id":"U_kgDOB0zlvA","is_bot":false,"login":"tiffanyxgu","name":""},"headRefName":"tg-implement-myreviews-page","number":50,"title":"tg-implemented MyReviews Index page","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-08/pull/50"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"aliasApproval","number":41,"title":"HS - alias approval table","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-08/pull/41"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"reviewForm","number":29,"title":"HS - add create form for reviews with stars, comments, date; create post review page","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-08/pull/29"}]
