
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-dining-s25-08
owner: ucsb-cs156-s25
repo_name: proj-dining-s25-08
pull_requests: [{"author":{"id":"U_kgDOCu9O7Q","is_bot":false,"login":"nathanalexander626","name":"Nathan Alexander"},"headRefName":"NA-moderator-role-backend","number":32,"title":"NA - adding all files needed to implement backend portion of moderator role","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-08/pull/32"},{"author":{"id":"U_kgDOB7-7uA","is_bot":false,"login":"selenazeng1","name":"Selena Zeng"},"headRefName":"sz-Reviews-Post-Placeholder","number":31,"title":"sz - Added Post Review Placeholder page and test page for it","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-08/pull/31"},{"author":{"id":"MDQ6VXNlcjgwNjE0Mzg1","is_bot":false,"login":"giozucca","name":""},"headRefName":"gl-actions-retry-loop","number":30,"title":"GL - Actions Retry Loop","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-08/pull/30"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"reviewForm","number":29,"title":"HS - add create form for reviews with stars, comments, date; fixed bug w/ menuitemtable","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-08/pull/29"}]
